version: '3.8'

services:
  vsa_backend:
    build: .
    container_name: vsa_backend
    ports:
      - "8081:8081"
    volumes:
      - sqlite_data:/app/data
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis    
    networks:
      - vsa_network
  

  redis:
    image: redis:7
    container_name: vsa_redis
    ports:
      - "6379:6379"
    networks:
      - vsa_network

volumes:
  sqlite_data:

networks:
  vsa_network:
    driver: bridge